<?php

/**
 * @file
 * Contains rep_profile_migrate.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.might_also_like_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Might Also Like Block for Product pages.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_block_theme() {

  return [
        'custom_block' => [
            'variables' => [
                'text' => [],
            ],
        ],
    ];

}


